apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: ms-producto-namespace
spec:
  capacity:
    storage: 10Gi  # Tamaño del volumen persistente
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # Puede variar según tu configuración de Kubernetes
  hostPath:
    path: /mnt/data/mongo  # Directorio en el host donde se almacenarán los datos de MongoDB